-- MySQL Script generated by MySQL Workbench
-- lun 13 may 2024 13:45:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myvinyls
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myvinyls` ;

-- -----------------------------------------------------
-- Schema myvinyls
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myvinyls` ;
USE `myvinyls` ;

-- -----------------------------------------------------
-- Table `myvinyls`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myvinyls`.`genre` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myvinyls`.`vinyl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myvinyls`.`vinyl` (
  `id_vinyl` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `album_name` VARCHAR(45) NOT NULL,
  `artist_name` VARCHAR(45) NULL,
  `price` INT NULL,
  `relase_date` DATE NULL,
  `id_genre` INT NOT NULL,
  PRIMARY KEY (`id_vinyl`),
  INDEX `fk_vinyl_genre1_idx` (`id_genre` ASC) VISIBLE,
  CONSTRAINT `fk_vinyl_genre1`
    FOREIGN KEY (`id_genre`)
    REFERENCES `myvinyls`.`genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myvinyls`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myvinyls`.`user` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `user_password` VARCHAR(100) NULL,
  `user_city` VARCHAR(45) NULL,
  `user_rol` VARCHAR(45) NOT NULL DEFAULT 'Cliente',
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myvinyls`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myvinyls`.`cart` (
  `id_cart` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `cart_closed` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_cart`),
  INDEX `fk_carrito_usuarios1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_usuarios1`
    FOREIGN KEY (`id_user`)
    REFERENCES `myvinyls`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myvinyls`.`cart_has_vinyls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myvinyls`.`cart_has_vinyls` (
  `id_cart` INT UNSIGNED NOT NULL,
  `id_vinyl` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cart`, `id_vinyl`),
  INDEX `fk_carrito_has_vinilos_vinilos1_idx` (`id_vinyl` ASC) VISIBLE,
  INDEX `fk_carrito_has_vinilos_carrito1_idx` (`id_cart` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_has_vinilos_carrito1`
    FOREIGN KEY (`id_cart`)
    REFERENCES `myvinyls`.`cart` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_vinilos_vinilos1`
    FOREIGN KEY (`id_vinyl`)
    REFERENCES `myvinyls`.`vinyl` (`id_vinyl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
